services:
  - type: web
    name: smartkrishi-backend
    env: python
    region: oregon
    plan: free
    buildCommand: cd backend && chmod +x render-build.sh && ./render-build.sh
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartkrishi-postgres
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: API_V1_STR
        value: /api/v1
      - key: FRONTEND_URL
        value: https://smart-krishi-nine.vercel.app

databases:
  - name: smartkrishi-postgres
    plan: free
    databaseName: smartkrishi_db_7uan
    user: smartkrishi_user
