version: '3.8'

services:
  db:
    image: postgres:15
    container_name: smartkrishi_postgres
    environment:
      POSTGRES_USER: smartkrishi_user
      POSTGRES_PASSWORD: smartkrishi_password
      POSTGRES_DB: smartkrishi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
